name:                wave-function-collapse
version:             0.1.0.0
github:              "ChrisPenner/wave-function-collapse"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/wave-function-collapse#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- vector
- logict
- fgl
- raw-strings-qq
- containers
- mtl
- adjunctions
- distributive
- hspec
- monad-dijkstra
- transformers
- MonadRandom
- random-shuffle
- nonempty-containers
- psqueues

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

executables:
  wave-function-collapse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-p
    dependencies:
    - wave-function-collapse

tests:
  wave-function-collapse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wave-function-collapse
