name:                mad-props
version:             0.1.0.0
github:              "ChrisPenner/mad-props"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/mad-props#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- raw-strings-qq
- containers
- mtl
- transformers
- MonadRandom
- random-shuffle
- psqueues
- logict
- mono-traversable
- unliftio
- async

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -O2

executables:
  sudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mad-props
    - ansi-terminal
